### ISSUE TITLE
slider组件无法点击比当前值更小的地方

### ISSUE THREAD

**Issue by zzlazy** [FatGe/UI-Library#3]
挺厉害的写法，让人眼前一亮~~~

问题是： max： 20 - min: 0 - value: 10，体现在页面上时，比10小的部分点击没有反应，原生的range可以随意点击

![image](https://user-images.githubusercontent.com/34973898/54679164-94a04680-4b41-11e9-8074-03bd963e11b6.png)

**Comment by zzlazy** [comment]
原生组件可以随意点击

**Comment by FatGe** [comment]
fix,[commit](https://github.com/FatGe/UI-Library/commit/94ecab2fe338d4b98c9528c9b5ed75f35ddbb89f)
